server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true
    username: root
    password: Suraj@1629
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # eureka:
    #  instance:
    #    prefer-ip-address:true
    #  client:
    #   fetch-registry:true
    #   register-with-eureka:true

    #  service-url:
    #   defaultZone:http://localhost:8761/eureka 

  config:
    import: configserver:http://localhost:8085


# acuator configuration

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health
  
  endpoint:
    health:
      show-details: always

# circuit breaker 

# resilience4j:
#   circuitbreaker:
#     instances:
#       ratingHotelBreaker:
#         registerHealthIndicator: true
#         eventConsumerBufferSize: 10
#         failureRateThreshold: 50
#         minimumNumberOfCalls: 5
#         automaticTransitionFromOpenToHalfOpenEnabled: true
#         waitDurationInOpenState: 6s
#         permittedNumberOfCallsInHalfOpenState: 3
#         slidingWindowSize: 10
#         slidingWindowType: COUNT_BASED

            
    
